---
version: "3"
services:
  expressvpn:
    image: polkaned/expressvpn
    container_name: expressvpn
    restart: unless-stopped
    ports:
      # ports from which container that uses expressvpn connection will be available in local network
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
      - 6789:6789
    environment:
      - ACTIVATION_CODE=EJDXCHJMRPAF7KMPFXSICRH # Activation Code from ExpressVPN https://www.expressvpn.com/support/troubleshooting/find-activation-code/
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
      - NZBGET_USER=admin #optional
      - NZBGET_PASS=admin #optional      
    volumes:
      - ${DOCKER_DIR}/nzbget:/config
      - ${DOWNLOAD_DIR}/usenet:/data/usenet:rw
    network_mode: service:expressvpn
    depends_on:
      - expressvpn    

  sonarr:
    image: cr.hotio.dev/hotio/sonarr:release
    container_name: sonarr
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}/sonarr:/data
      - ${DOWNLOAD_DIR}/usenet:/data/usenet      

  radarr:
    image: cr.hotio.dev/hotio/radarr:release
    container_name: radarr
    restart: always
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}/radarr:/data
      - ${DOWNLOAD_DIR}/usenet:/data/usenet

  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr:testing
    container_name: prowlarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/prowlarr:/config
    ports:
      - 9696:9696 
      
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
      - VERSION=docker
      - PLEX_CLAIM=claim-St36LNdkwNvshvnsB2ge
    ports:
      - 32400:32400
    volumes:
      - ${DOCKER_DIR}/plex:/config
      - ${DOWNLOAD_DIR}/sonarr:/tv
      - ${DOWNLOAD_DIR}/radarr:/movies
      - ${DOWNLOAD_DIR}/lidarr:/music      
    restart: unless-stopped   

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/bazarr:/config
      - ${DOWNLOAD_DIR}/sonarr:/tv
      - ${DOWNLOAD_DIR}/radarr:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/lidarr:/config
      - ${DOWNLOAD_DIR}/lidarr:/data
      - ${DOWNLOAD_DIR}/usenet:/data/usenet
      - ${DOWNLOAD_DIR}/music:/music
    ports:
      - 8686:8686
    restart: unless-stopped


  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/tdarr:/app/server/config
      - /mnt/disk1/media_data:/media
    ports:
      - 8265:8265
    restart: unless-stopped  
    networks:
      - media_network

    
  tdarr_node:
    image: haveagitgat/tdarr_node:latest
    container_name: tdarr_node
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
      - serverIP=tdarr
      - serverPort=8266      
    volumes:
      - ${DOCKER_DIR}/tdarr_node:/app/server/config
      - /mnt/disk1/media_data:/media
    ports:
      - 8267:8267
    restart: unless-stopped
    networks:
      - media_network

  readarr:
    image: linuxserver/readarr:0.3.4-develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/readarr:/config
      - ${DOWNLOAD_DIR}/books:/books
    ports:
      - 8787:8787
    restart: unless-stopped

  calibre:
    image: aptalca/docker-rdp-calibre:latest
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Australia/Sydney
    volumes:
      - ${DOCKER_DIR}/calibre:/config
      - ${DOWNLOAD_DIR}/calibre_library:/books
    ports:
      - 8089:8089
      - 8090:8090
    restart: unless-stopped

      

networks:
  media_network:

